### ISSUE TITLE
[UI TASK] Server Info Screen

### ISSUE THREAD

**Issue by yugeshjain** [Anmol92verma/DiscordJetpackCompose#33]
![Server Info Screen](https://user-images.githubusercontent.com/45540677/177931831-f9136a63-b796-4557-a93c-891f3a22d771.jpg)

**Comment by shubhamsinghshubham777** [comment]
@Anmol92verma Already covered with https://github.com/Anmol92verma/DiscordJetpackCompose/pull/56
