### ISSUE TITLE
Setup Colors and Font

### ISSUE THREAD

**Issue by Anmol92verma** [Anmol92verma/DiscordJetpackCompose#4]
https://gist.github.com/Anmol92verma/fdaece0b26c812c73391c564079fcf1f

[Setup Font](https://pcstrike.com/discord-font/#:~:text=The%20font%20that%20is%20used,font's%20appearance%20via%20Discord's%20settings.)

**Comment by shubhamsinghshubham777** [comment]
@Anmol92verma Do we want to create a new `Colors.kt` file or are we okay in using `colorResource(id=xxx)`?

**Comment by Anmol92verma** [comment]
@shubhamsinghshubham777 we need Colors.kt and we need to provide colors from MaterialTheme
